# Generated by Django 3.2.5 on 2021-07-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superheroe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alter_ego', models.CharField(max_length=50)),
                ('prim_superpower', models.CharField(max_length=50)),
                ('secon_superpower', models.CharField(max_length=50)),
                ('catchphrase', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Superheroes',
        ),
    ]
