# Generated by Django 3.2.5 on 2021-07-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroesapp', '0002_auto_20210729_1519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Superheroe',
            new_name='Superhero',
        ),
    ]
